### ISSUE TITLE
[Front] 레이아웃 - 회원가입 페이지

### ISSUE THREAD

**Issue by jeongdxxn** [codestates/FilmStorage#108]
### ISSUE
- Group:  `Client`
- Type: `bug`, `feature`, `delete`
- Detail: 회원가입 페이지 레이아웃 구현

### TODO
1. [ ] 사진 등록 레이아웃 구현
2. [ ] 이메일/ 닉네임/ 비밀번호/ 비밀번호 확인/ 휴대폰 번호 입력 창 레이아웃 구현
3. [ ] 이용약관 체크박스/ 상세 내용 모달 창 구현
4. [ ] 회원가입 버튼 구현
5. [ ] (option)소셜 로그인 버튼 구현
