### ISSUE TITLE
[Front] 레이아웃 - 필름토크 게시글 작성 페이지

### ISSUE THREAD

**Issue by jeongdxxn** [codestates/FilmStorage#112]
### ISSUE
- Group:  `Client`
- Type:  `feature`
- Detail: 필름토크 게시글 작성 페이지 레이아웃 구현

### TODO
1. [ ] 카테고리 선택 레이아웃 구현
2. [ ] 제목/ 내용 작성 레이아웃 구현
3. [ ] 돌아가기/ 작성완료 버튼 구현

### Estimated time
> Pick one
