### ISSUE TITLE
[Front] 레이아웃 - 아이디 찾기 페이지

### ISSUE THREAD

**Issue by jeongdxxn** [codestates/FilmStorage#114]
### ISSUE
- Group:  `Client`
- Type: `feature`
- Detail: 아이디 찾기 페이지 레이아웃 구현

### TODO
1. [x] 닉네임/ 전화번호 입력창 구현
2. [x] 오류 메세지 출력 레이아웃 구현
3. [x] 아이디 찾기 버튼 구현
4. [x] 아이디 찾기 버튼을 눌렀을 때 회원 아이디를 출력하는 페이지 구현(아이디 표시 /로그인하기 버튼)
