### ISSUE TITLE
[Front] 레이아웃 - 필름 취향 찾기 페이지

### ISSUE THREAD

**Issue by jeongdxxn** [codestates/FilmStorage#119]
### ISSUE
- Group:  `Client`
- Type: `feature`
- Detail: 필름 취향 찾기 페이지 레이아웃 구현

### TODO
1. [ ] 취향 테스트 진행 단계 표시 바 구현
2. [ ] 취향 테스트 선택 버튼 레이아웃 구현
3. [ ] 테스트 완료 후 결과 출력 레이아웃 구현(필름사진/ 이름 /정보)
4. [ ] 필름 로그페이지로 이동하는 버튼 구현(결과로 나온 필름 이름 표시)
