### ISSUE TITLE
[Front]레이아웃 - 이달의 필름 날씨에 따른 이모티콘 및 내용 변경 

### ISSUE THREAD

**Issue by sud665** [codestates/FilmStorage#123]
### ISSUE
- Group:  `Client`
- Type: `Design`
- Detail: 이달의 필름 날씨에 따른 이모티콘 수집

### TODO
1. [ ] 이달의 필름 날씨에 따른 이모티콘 수집
2. [ ] 날씨에 따른 추천 멘트 작성 변경 
3. [ ] 필름 내용 수집
