### ISSUE TITLE
[Front] 필름 취향 찾기 테스트 기능 구현 

### ISSUE THREAD

**Issue by sud665** [codestates/FilmStorage#176]
### ISSUE
- Group:  `Client`
- Type:  `feature`
- Detail: 필름 취향 찾기 테스트 기능 구현 

### TODO
1. [ ] 필름 관련 더미데이터 수집 
2. [ ] 단계별 컴포넌트 구현
3. [ ] 단계별로 상단 바가 채워지는 에니메이션 구현 

### Estimated time
> Pick one
