### ISSUE TITLE
[Front] 필름 스팟 페이지/ 오늘의 필름 페이지 추가 와이어프레임 만들기

### ISSUE THREAD

**Issue by jeongdxxn** [codestates/FilmStorage#227]
### ISSUE
- Group:  `Client`
- Type: `feature`
- Detail: 필름 스팟 페이지 추가/ 오늘의 필름 페이지 수정

### TODO
1. [ ] 필름 스팟 네비바/메인에 바로가기 추가
2. [ ] 필름 스팟 페이지 레이아웃 추가
3. [ ] 오늘의 필름 레이아웃 수정

### `1h`
