### ISSUE TITLE
[Front] 레이아웃 - 계정관리 페이지

### ISSUE THREAD

**Issue by sud665** [codestates/FilmStorage#24]
### ISSUE
- Group:  `Client`
- Type: `design`
- Detail: 회원가입, 로그인, 로그아웃, 마이페이지 레이아웃 

### TODO
1. [x] 사진 수정 레이아웃 구현
2. [x] 계정관리 페이지 프로필 편집/ 비밀번호 변경 탭 구현
3. [x] 프로필 편집 탭 닉네임/ 유저 아이디 변경 구현
4. [x] 비밀번호 변경 탭 현재 비밀번호/ 변경 비밀번호 / 비밀번호 확인 구현
5. [x] 정보 수정하기 버튼 구현
6. [x] 탈퇴하기 버튼 구현
