### ISSUE TITLE
[Front]레이아웃 - 필름로그 상세페이지 

### ISSUE THREAD

**Issue by jeongdxxn** [codestates/FilmStorage#27]
### ISSUE
- Group:  `Client`
- Type: `feature`
- Detail: 필름로그 상세페이지 레이아웃 작성

### TODO
1. [x] 해당 이미지 / 유저 정보 /  필름태그 / 좋아요 수 / 조회수 
2. [x] 해당 이미지 내용 
3. [x] 수정하기/ 삭제하기 버튼 구현 
4. [x] 댓글 박스
