### ISSUE TITLE
[Front] 레이아웃 - 필름토크 게시글 보기 페이지

### ISSUE THREAD

**Issue by jeongdxxn** [codestates/FilmStorage#29]
### ISSUE
- Group:  `Client`
- Type: `feature`
- Detail: 필름토크 게시글 페이지 레이아웃 작성

### TODO
1. [ ] 카테고리/ 제목 / 내용 / 유저 정보 / 날짜 / 조회수 레이아웃 구현
2. [ ] 글 수정/ 삭제 버튼 구현
3. [ ] 댓글 리스트 / 댓글 입력 창 구현
4. [ ] 댓글 수정/ 삭제 버튼 구현 
5. [ ] 댓글 쓰기 버튼 구현
6. [ ] 삭제 버튼 클릭 시 확인 모달 창 구현

### `2h`
