### ISSUE TITLE
[Front] 메인페이지 - 소개글에 따른 페이지 이동 링크 구현 

### ISSUE THREAD

**Issue by sud665** [codestates/FilmStorage#36]
### ISSUE
- Group:  `Client`
- Type:  `feature`
- Detail:  메인페이지의 소개글에 따른 페이지 이동 기능 구현 

### TODO
1. [x] 필름로그 페이지 이동 
2. [x] 오늘의 필름 페이지 이동 
3. [x] 필름 취향 테스트 페이지 이동
