### ISSUE TITLE
[Front] 갤러리 상세페이지 - 사진 수정 및 삭제하기 기능

### ISSUE THREAD

**Issue by jeongdxxn** [codestates/FilmStorage#45]
### ISSUE
- Group:  `Client`
- Type:  `feature`
- Detail: 사진 업로더에 수정 및 삭제하기 기능 부여

### TODO
1. [x] 사진 / 내용 수정 기능
2. [x] 사진 / 내용 삭제 기능
3. [x] 사진 업로더만 수정 및 삭제 가능하게 구현(사진 업로더에게 수정/ 삭제 버튼 표시)
