### ISSUE TITLE
[Deploy] 테스트 배포 진행

### ISSUE THREAD

**Issue by SsankQ** [codestates/FilmStorage#58]
### ISSUE
- Group:  `Deploy`
- Type: `Test`
- Detail: Client / Server에 각각 Hello World 출력하며 테스트 배포 진행

### TODO
1. [x] 구입한 도메인으로 진입 시 보안 프로토콜이 잘 적용되어 있는지 체크 (ELB / CloudFront / Route53)
3. [x] `BuildSpec.yml`을 이용해 Client 배포 자동화가 잘 설정되어 있는지 체크
4. [x] `AppSpec.yml`을 이용해 Server 배포 자동화가 잘 설정되어 있는지 체크
5. [x] 배포 자동화 LifeCycle이 정상적으로 잘 돌아가는지 체크
