### ISSUE TITLE
[Front] 마이갤러리 페이지 - 사진 업로드 기능 구현

### ISSUE THREAD

**Issue by jeongdxxn** [codestates/FilmStorage#66]
### ISSUE
- Group:  `Client`
- Type: `feature`
- Detail: 마이갤러리 페이지 사진 업로드 기능 구현

### TODO
1. [ ] 로컬에 있는 사진 선택해서 업로드 하는 기능 구현
2. [ ] 필름 종류 선택하는 기능 구현
3. [ ] 내용 작성하는 기능 구현
4. [ ] 사진 추가 버튼을 눌러서 POST 요청으로 데이터 보내기
