### ISSUE TITLE
[Front] 갤러리/게시판 더미데이터 만들기

### ISSUE THREAD

**Issue by jeongdxxn** [codestates/FilmStorage#68]
### ISSUE
- Group:  `Client`
- Type: `dummy data`
- Detail: 갤러리/게시판 더미데이터 만들기

### TODO
1. [ ] 필름 종류 데이터 조사 
2. [ ] 갤러리 게시글 더미데이터 작성
3. [ ] 게시판 게시글 더미데이터 작성
